#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#HTTP Settings
http_host: "your_domain"
http_conf: "your_domain.conf"
http_port: "80"