service: serverless-template

frameworkVersion: '2'

variablesResolutionMode: 20210219
configValidationMode: error
useDotenv: true

package:
  individually: true

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  lambdaHashingVersion: 20201221
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    TABLE_NAME: ${self:custom.tableName}
    REGION: ${opt:region, self:provider.region}
    DB_ENDPOINT: https://dynamodb.${opt:region, self:provider.region}.amazonaws.com

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TABLE_NAME}"
  httpApi:
    name: 'template-api-gateway-${opt:stage, "dev"}'
    cors:
      allowedMethods:
        - GET
        - OPTIONS
        - POST
  apiGateway:
    minimumCompressionSize: 1024
    shouldStartNameWithService: true

custom:
  bundle:
    linting: true
  serverless-offline:
    host: 0.0.0.0
  tableName: test-data-table-${opt:stage, 'dev'}

functions:
  getUser:
    handler: src/server.handler
    memorySize: 128
    events:
      - httpApi:
          path: /user
          method: get

  insertUser:
    handler: src/server.handler
    memorySize: 128
    events:
      - httpApi:
          path: /user
          method: post

resources:
  Resources:
    DynamoDBTable: ${file(./resource/dynamodb/DynamoDBTable.yml)}