version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
    - npm install --silent --no-progress -g serverless@~2.29.0

  pre_build:
    commands:
    - cd $CODEBUILD_SRC_DIR/serverless-app
    - npm install --silent --no-progress
    - npm run test

  build:
    commands:
    - cd $CODEBUILD_SRC_DIR/serverless-app
    - npm run migrate:latest
    - serverless deploy -c $ServerlessFile --stage $EnvName -v -r $AwsRegionDeploy
