version: "3.8"

services:

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    networks:
      - database
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]

networks:
  database:
