---
dependency:
  name: galaxy
driver:
  name: vagrant
platforms:
  - name: instance
    box: fedora/32-cloud-base
    memory: 1024
    cpus: 1
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: "'vagrant'"
provisioner:
  name: ansible
  connection_options:
    ansible_ssh_user: vagrant
    ansible_become: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .